### ISSUE TITLE
Add to Readme: Improve live reload for blazor by disabling linking for debug mode

### ISSUE THREAD

**Issue by codeclash** [RickStrahl/Westwind.AspnetCore.LiveReload#11]
Tip: add this, should/could speed up incremental builds:

``` xml
<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>
```

See [https://github.com/aspnet/AspNetCore/issues/5456#issuecomment-518631414](https://github.com/aspnet/AspNetCore/issues/5456#issuecomment-518631414)

**Comment by RickStrahl** [comment]
Does that work any better? Last I played around with this the reload still was incredibly slow due to the full server reload.

Looking at that thread I'm not sure what I'm looking at in regards to the note you posted here. Can you provide more context (sorry - haven't been keeping up with Blazor recently).

**Comment by codeclash** [comment]
@RickStrahl  I was assuming that disabling linking for debug builds might speed up things a bit (or make re-builds less slow... :-) 
A shot in the dark to be honest, seemed legit. I'll try with and without that setting and will let you know if it has any perceivable impact.
