### ISSUE TITLE
Vanilla asp.net core site not running LiveReload correctly

### ISSUE THREAD

**Issue by hsankala** [RickStrahl/Westwind.AspnetCore.LiveReload#31]
# LivereloadTryOut
LivereloadTryOut

I'm trying to get [RickStrahl - Westwind.AspnetCore.LiveReload][1] package to work on a vanilla asp.net solution. I have followed the instructions as the github readme [here][1]

In `Startup.ConfigureServices()` I have added

```
services.AddLiveReload(config =>
{
    // optional - use config instead
    //config.LiveReloadEnabled = true;
    //config.FolderToMonitor = Path.GetFullname(Path.Combine(Env.ContentRootPath,"..")) ;
});
```

In `Startup.Configure()` I have added 

```
app.UseLiveReload();

app.UseStaticFiles();
app.UseMvcWithDefaultRoute();
```

Configuration Settings have been added:
```
{
  "LiveReload": {
    "LiveReloadEnabled": true,
    "ClientFileExtensions": ".cshtml,.css,.js,.htm,.html,.ts,.razor,.custom",
    "ServerRefreshTimeout": 3000,
    "WebSocketUrl": "/__livereload",
    "WebSocketHost": "ws://localhost:5000",
    "FolderToMonitor": "~/"
  }
}
```

I've uploaded my vanilla asp.net core start project with RickStrahl - Westwind.AspnetCore.LiveReload nuget package and configuration to a public github repo [here][2]

I'm simply running this website in Visual studio IISExpress and updating the CSS file in the wwwroot folder, but the browser does not update with the changes

  [1]: https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload
  [2]: https://github.com/hsankala/LivereloadTryOut

**Comment by RickStrahl** [comment]
Hmmm... the problem is IIS Express. It's using out of process hosting which screws up the URL to find the Web Socket server. if you bring up the dev tools you'll see that the URL is pointing at the wrong location.

To fix this:

* Run the application with Kestrel (using the `Vanilla_ASP.NET_Core_Site` preset in the LaunchSettings and on the run button.
* Explicitly specify the URL to the Web Socket server which should be:
`config.WebSocketHost = "wss://localhost:44331";` if you're running IIS Express and SSL

Either of these works. 

There's a bug there as LiveReload should be automatically retrieving the URL, but the problem is with IIS Express and out of process hosting, the URL will be the proxy forwarded URL which is not the actual host but the Kestrel proxy call which is not right. I'll take a look and see what I can see there.

However, if you really want to use this library to its fullest extent you will want to use Kestrel in combination with `dotnet watch run` from the command line to automatically recompile code changes as well as UI page changes.

**Comment by RickStrahl** [comment]
Ohhh... duh. You hard coded the WebSocket host to `ws://localhost:5000` in config. Take that out and set it to `null`. That should only be set to `null` or not be set at all. Only set the settings you need to actually override.

```json
"LiveReload": {
    "LiveReloadEnabled": true,
    "ClientFileExtensions": ".cshtml,.css,.js,.htm,.html,.ts,.razor,.custom",
    "ServerRefreshTimeout": 3000,
    "WebSocketUrl": "/__livereload",
    "WebSocketHost": null,  // this!
    "FolderToMonitor": "~/"
  }
```

The two WebSocket settings shouldn't be set except when you need to override them explicitly (which should be never pretty much)...

**Comment by hsankala** [comment]
ahhhh thanks @RickStrahl I blindly copied the config on your main installation guide.  Sorted thanks. Might be worth updating on your code guide too, so no-one else blindly does the same as me.

**Comment by RickStrahl** [comment]
Ah thanks... fixed that too in the docs, setting the value to 0. Yeah that would really screw up people.
