### ISSUE TITLE
Consider renaming from  `Westwind.AspnetCore.LiveReload` to `Westwind.AspNetCore.LiveReload`

### ISSUE THREAD

**Issue by tjrobinson** [RickStrahl/Westwind.AspnetCore.LiveReload#34]
To be consistent with other ASP.NET Core libraries, namely the Microsoft ones, e.g. 
[Microsoft.AspNetCore](https://www.nuget.org/packages/Microsoft.AspNetCore/), would it be an idea to change the name of the repository and package from  `Westwind.AspnetCore.LiveReload` to `Westwind.AspNetCore.LiveReload`?

**Comment by RickStrahl** [comment]
Yes the naming needs to be cleaned up in the various projects and the solution at minimum to be consistent. I've been running into issues when opening on non-Windows platforms due to consistencies. Personally I prefer the `.Aspnet` rather than `.AspNet`. 

I'll do this next time I'll do some project refactoring which is coming as I pull the LiveReloadServer out of this project.
