### ISSUE TITLE
Page reloads without change on Ubuntu

### ISSUE THREAD

**Issue by vladtreny** [RickStrahl/Westwind.AspnetCore.LiveReload#37]
Hello,

Thank you for this extension.

I run it on Ubuntu, for example, with that
dotnet watch run debug --environment "Development" 

And the page reloads without any change in code.

asp.net 3.1
Ubuntu 19.10

          services.AddLiveReload(config =>
            {
                // optional - use config instead
                config.LiveReloadEnabled = true;
                config.ClientFileExtensions = ".cs";
                config.FolderToMonitor = Environment.ContentRootPath;
            });

**Comment by RickStrahl** [comment]
Which page? The way you have this configured it also looks like it will never trigger at all because .cs is not a client extension? If you want to restart on .cs files in your server side application you can just use `dotnet-watch` - you don't need this component for that.

Also not that .NET 5 Preview 8 and later has some built-in functionality similar based on this component. It's possible that there's overlap between the two and that might be causing the problem.
