### ISSUE TITLE
UseLiveReload() breaks UseDeveloperExceptionPage()

### ISSUE THREAD

**Issue by Andypro1** [RickStrahl/Westwind.AspnetCore.LiveReload#39]
When using 

```
if(env.IsDevelopment()) {
   app.UseDeveloperExceptionPage();
}
```

followed later by

```
app.UseLiveReload();
```

All pages which throw errors return a generic protocol error rather than the developer exception page.  

Possible this may be related to the fact that the developer exception page can't be invoked if a response stream is started (according to the dotnet repo).

_Edit:  This is with the latest Westwind.AspnetCore.LiveReload version 0.2.10 and the latest .NET 5.0 preview (rc1, I think)._

**Comment by RickStrahl** [comment]
Yes I can duplicate that, but I'm not sure if I can fix this. Ideally you have to put `app.UseLiveReload()` before any output generating component. Otherwise there will be problems because you may end up with half finished requests - as with the developer page.

The reason for this I think is this:

* App runs and processes your request
* Then an error occurs
* Developer page rewrites the URL and starts a new request through the pipeline

Because the pipeline runs FIFO, the inner request (LiveReload) gets aborted and all state associated is lost.

Guessing here based on behavior I see when debugging: 

The original request is essentially aborted and a new one started. Now when the middleware gets to the end of hte request the original output stream hasn't been set yet if the middleware gets a hold of the request too late and so it basically took over the output stream but now that original stream is no longer there. 

It works when `UseLiveReload()` is fired **before** any other requests, because the original stream is capture and apparently that's still available during the rewrite.

So you basically need to make sure `UseLiveReload()` is set before any output generating middleware.

Side effect:

In the process of debugging this I managed to figure out how to have the error page refresh now, so that's a bonus. So now when an error fires and the developer error page shows, and you then fix the code, the error page will refresh and show the fixed (or newly re-broken :smile:) page.

**Comment by Andypro1** [comment]
Thanks Rick.  `UseLiveReload()` does indeed work when placed first in `Configure()`.
